"""
  Copyright 2024 KU Leuven
  Ryan Antonio <ryan.antonio@esat.kuleuven.be>

  Description:
  This tests the ROM item memory where each item is generated by an LFSR.
"""

from util import setup_and_run, gen_randint, get_root

import cocotb
from cocotb.triggers import Timer
import numpy as np
import pytest
import sys

# Add hdc utility functions
vsax_path = get_root() + "/lib/"
print(f"Adding VSAX library path: {vsax_path}")
sys.path.append(vsax_path)
import vsax  # noqa: E402


# Some local parameters for testing
HV_DIM = 128
NUM_ITEM = 32
NUM_SEL = 4
NUM_TEST = 10
BASE_SEED = 42
HV_TYPE = "binary"
GEN_TYPE = "lfsr"


# Set inputs to 0
def clear_inputs(dut):
    for i in range(NUM_SEL):
        dut.im_sel_i[i].value = 0
    return


def random_inputs(dut):
    for i in range(NUM_SEL):
        dut.im_sel_i[i].value = gen_randint(0, NUM_ITEM - 1)
    return


# Preperation of golden values
lfsr_im = vsax.hv_gen_orthogonal_im(
    num_items=NUM_ITEM,
    hv_size=HV_DIM,
    hv_type=HV_TYPE,
    gen_type=GEN_TYPE,
    gen_lfsr_base_seed=BASE_SEED,
)


@cocotb.test()
async def rom_lfsr_item_memory_dut(dut):
    cocotb.log.info(" ------------------------------------------ ")
    cocotb.log.info("             Testing LFSR ROM               ")
    cocotb.log.info(" ------------------------------------------ ")

    # Initialize input values
    clear_inputs(dut)

    # Wait one cycle for reset
    await Timer(1, "ns")

    cocotb.log.info(" ------------------------------------------- ")
    cocotb.log.info("          Outputting Random Selects          ")
    cocotb.log.info(" ------------------------------------------- ")

    for i in range(NUM_TEST):
        random_inputs(dut)
        await Timer(1, "ns")
        for j in range(NUM_SEL):
            actual = np.array(list(str(dut.im_rdata_o[j].value)), dtype=int)
            expected = lfsr_im[dut.im_sel_i[j].value]
            match = np.array_equal(actual, expected)
            if not match:
                print(f"  actual:   {actual}")
                print(f"  expected: {expected}")
            assert match, f"Test {i}, port {j}: output mismatch!"

    await Timer(10, "ns")


# Actual test run
@pytest.mark.parametrize(
    "parameters",
    [
        {
            "HVDimension": str(HV_DIM),
            "NumTotIm": str(NUM_ITEM),
            "Seed": str(BASE_SEED),
            "NumPorts": str(NUM_SEL),
        }
    ],
)
def test_rom_lfsr_item_memory(simulator, parameters, waves):
    verilog_sources = ["/rtl/item_memory/rom_lfsr_item_memory.sv"]

    toplevel = "rom_lfsr_item_memory"

    module = "test_rom_lfsr_item_memory"

    setup_and_run(
        verilog_sources=verilog_sources,
        toplevel=toplevel,
        module=module,
        simulator=simulator,
        parameters=parameters,
        waves=waves,
    )
