name: HW-SW Unit Tests
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  rtl-unit-tests-vlt:
    name: Unit Tests using Verilator
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuleuven-micas/hypercorex:main
    steps:
      - uses: actions/checkout@v4
      - name: Running Pytest
        # We ignore slow system tests
        run: |
          pytest -n $(nproc) --dist=loadfile \
          --ignore=tests/test_tb_hypercorex.py \
          --ignore=tests/test_hypercorex_csr.py \
          --ignore=tests/test_hypercorex_am_search.py \
          --ignore=tests/test_hypercorex_char_recog.py \
          --ignore=tests/test_hypercorex_ortho_im_only.py \
          --ignore=tests/test_hypercorex_isolet_recog.py \
          --ignore=tests/test_hypercorex_digit_recog.py \
          --ignore=tests/test_hypercorex_ucihar_recog.py \
          --ignore=tests/test_hypercorex_dna_recog.py \
          --ignore=tests/test_hypercorex_lang_recog.py \
          --ignore=tests/test_hypercorex_char_recog_data_slice.py

  rtl-system-tests-vlt:
    name: System Tests using Verilator
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuleuven-micas/hypercorex:main
    steps:
      - uses: actions/checkout@v4
      - name: Running Pytest
        # We initialize testbench directory test first
        # Then run all other tests in parallel
        run: |
          pytest tests/test_tb_hypercorex.py && \
          pytest -n $(nproc) --dist=loadfile \
          tests/test_hypercorex_csr.py \
          tests/test_hypercorex_am_search.py \
          tests/test_hypercorex_char_recog.py \
          tests/test_hypercorex_ortho_im_only.py \
          tests/test_hypercorex_char_recog_data_slice.py

  sw-test:
    name: Test Compiler for ASM
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuleuven-micas/hypercorex:main
    steps:
      - uses: actions/checkout@v4
      - name: Running Compiler
        run: |
          python3 sw/hypercorex_compiler.py
